### ISSUE TITLE
[CORREÇÃO] Place model

### ISSUE THREAD

**Issue by italopaiva** [italopaiva/EuVou#10]
* Métodos set devem ser privados;
* Validar endereço no setAddress (corrigir o nome que ta lá também);
* Não utilizar operador ternário (método setEvaluate());
* Colocar chaves nos 'ifs';

**Comment by VinyPinheiro** [comment]
Existem dados abertos que não tem endereço, logo o campo pode ser vazio. Seria validar o que?

**Comment by italopaiva** [comment]
Era só caso precisasse. Mas se não faz sentido ter validação, beleza..
