### ISSUE TITLE
Implementar Parser

### ISSUE THREAD

**Issue by Emiliemorais** [italopaiva/EuVou#5]
Implementação do parser dos arquivos:

esporte.csv
lazer.csv
parques.csv
pontos-turisticos.csv
culturaeduca_museus.csv
culturaeduca_teatros.csv
culturaeduca_pontosdecultura.csv

**Comment by VinyPinheiro** [comment]
Existem dados duplicados na base de dados e os dados de funcionamento não entraram em nenhuma tupla

**Comment by italopaiva** [comment]
Corrigido!
